# -*- coding: utf-8 -*-
"""heritage_crowd_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnGoodcYm3BCySZvwea1mCMHGyaN-309
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# 1. Define the parameters for the heritage trail
checkpoints = ['Mukteswar Temple', 'Parsurameswara Temple', 'Bindu Sagar', 'Lingaraj Temple', 'Rajarani Temple']
weather_conditions = ['Clear', 'Cloudy', 'Rainy', 'Humid']
time_slots = ['06:00', '09:00', '12:00', '15:00', '18:00']

# 2. Generate 5,000 rows of synthetic data
data = []
start_date = datetime(2025, 1, 1)

for _ in range(5000):
    # Randomize base variables
    date = start_date + timedelta(days=random.randint(0, 365))
    day_of_week = date.weekday() # 0 = Monday, 6 = Sunday
    is_weekend = 1 if day_of_week >= 5 else 0
    is_festival = np.random.choice([0, 1], p=[0.95, 0.05]) # 5% chance of a festival day

    checkpoint = random.choice(checkpoints)
    weather = random.choice(weather_conditions)
    time = random.choice(time_slots)
    temperature = random.randint(22, 40) # Typical Odisha temperatures

    # 3. Create mathematical correlations for realistic crowd density
    base_crowd = random.randint(20, 100)

    # Crowds spike on weekends and festivals
    if is_weekend: base_crowd += random.randint(50, 150)
    if is_festival: base_crowd += random.randint(200, 400)

    # Crowds drop during extreme heat or rain
    if temperature > 36: base_crowd -= random.randint(20, 50)
    if weather == 'Rainy': base_crowd -= random.randint(40, 80)

    # Crowds are higher in early morning (06:00) or evening (18:00)
    if time in ['06:00', '18:00']: base_crowd += random.randint(30, 80)

    # Ensure crowd doesn't drop below zero
    final_crowd = max(5, base_crowd)

    data.append([date.strftime('%Y-%m-%d'), is_weekend, is_festival, checkpoint, weather, temperature, time, final_crowd])

# 4. Export to CSV
df_crowd = pd.DataFrame(data, columns=['Date', 'Is_Weekend', 'Is_Festival', 'Checkpoint', 'Weather', 'Temperature_C', 'Time_Slot', 'Crowd_Density'])
df_crowd.to_csv('data/heritage_crowd_data.csv', index=False)
print("Successfully generated 'data/heritage_crowd_data.csv' with 5,000 rows.")

# 1. Create templates for different sentiments
positive_reviews = [
    "Absolutely beautiful architecture at {}. The stone carvings are breathtaking.",
    "Very peaceful morning walk around {}. Highly recommend visiting early.",
    "The guide explained the history of {} perfectly. A must-see cultural site!",
    "Incredible heritage and well maintained. Loved the atmosphere at {}."
]

negative_reviews = [
    "It was way too crowded at {}. Couldn't even walk around properly.",
    "The area around {} was quite dirty and unmanaged today.",
    "Terrible experience, the heat was unbearable and there was no shade near {}.",
    "Too many hawkers and traffic noise ruined the peace at {}."
]

neutral_reviews = [
    "Visited {} today. It was okay, standard historical site.",
    "The architecture at {} is nice, but we only stayed for 15 minutes.",
    "Just a quick stop at {} during our city tour. Nothing special.",
    "It's fine. Make sure to bring water if you visit {}."
]

# 2. Synthesize 1,000 randomized reviews
reviews_data = []

for _ in range(1000):
    sentiment = random.choice(['Positive', 'Negative', 'Neutral'])
    checkpoint = random.choice(checkpoints) # Reusing the checkpoints from Step 1

    if sentiment == 'Positive':
        text = random.choice(positive_reviews).format(checkpoint)
    elif sentiment == 'Negative':
        text = random.choice(negative_reviews).format(checkpoint)
    else:
        text = random.choice(neutral_reviews).format(checkpoint)

    reviews_data.append([text, sentiment])

# 3. Export to CSV
df_reviews = pd.DataFrame(reviews_data, columns=['Review_Text', 'Sentiment_Label'])
df_reviews.to_csv('data/heritage_tourist_reviews.csv', index=False)
print("Successfully generated 'data/heritage_tourist_reviews.csv' with 1,000 rows.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the generated dataset
print("Loading data for EDA...")
df = pd.read_csv('data/heritage_crowd_data.csv')

# Set the visual style for professional charts
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (15, 10)

# Create a 2x2 grid for our subplots
fig, axes = plt.subplots(2, 2)
fig.tight_layout(pad=5.0)

# --- Plot 1: Distribution of Crowds ---
# Insight: Are most days empty, or mostly crowded?
sns.histplot(df['Crowd_Density'], kde=True, color='royalblue', ax=axes[0, 0])
axes[0, 0].set_title('Distribution of Crowd Density', fontweight='bold')
axes[0, 0].set_xlabel('Number of People')
axes[0, 0].set_ylabel('Frequency')

# --- Plot 2: Impact of Weather on Crowds ---
# Insight: Proving that bad weather reduces foot traffic
sns.boxplot(x='Weather', y='Crowd_Density', data=df, palette='Set2', ax=axes[0, 1])
axes[0, 1].set_title('Crowd Density vs. Weather Conditions', fontweight='bold')
axes[0, 1].set_xlabel('Weather')
axes[0, 1].set_ylabel('Crowd Density')

# --- Plot 3: Crowds Across Different Times of Day ---
# Insight: Finding the peak operational hours
sns.pointplot(x='Time_Slot', y='Crowd_Density', data=df, color='crimson', markers="o", linestyles="-", errorbar=None, ax=axes[1, 0], order=['06:00', '09:00', '12:00', '15:00', '18:00'])
axes[1, 0].set_title('Foot Traffic by Time of Day', fontweight='bold')
axes[1, 0].set_xlabel('Time of Day')
axes[1, 0].set_ylabel('Average Crowd')

# --- Plot 4: Correlation Heatmap ---
# Insight: Finding the mathematical correlation between strictly numerical features
numerical_df = df[['Is_Weekend', 'Is_Festival', 'Temperature_C', 'Crowd_Density']]
sns.heatmap(numerical_df.corr(), annot=True, cmap='RdYlGn', vmin=-1, vmax=1, ax=axes[1, 1])
axes[1, 1].set_title('Feature Correlation Heatmap', fontweight='bold')

plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import joblib

# 1. Load the dataset
print("Loading data for preprocessing and training...")
df = pd.read_csv('data/heritage_crowd_data.csv')

# Drop the 'Date' column since it's just text and we already have Is_Weekend/Is_Festival
df = df.drop(columns=['Date'])

# 2. PREPROCESSING: Label Encoding (Text to Math)
# Here is the LabelEncoder you were asking about!
label_encoders = {}
categorical_cols = ['Checkpoint', 'Weather', 'Time_Slot']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # Store the encoder so we can save it

# Save the encoders so your final web app knows how to translate user inputs
joblib.dump(label_encoders, 'models/label_encoders.pkl')
print("✅ Saved label encoders to 'models/label_encoders.pkl'")

# 3. Define Features (X) and Target Variable (y)
X = df.drop(columns=['Crowd_Density'])
y = df['Crowd_Density']

# 4. Train-Test Split (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Model Training
print("\nTraining the Random Forest Regressor (Building 100 decision trees)...")
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 6. Model Evaluation
y_pred = rf_model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("\n--- Model Evaluation Results ---")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} people")
print(f"Mean Absolute Error (MAE): {mae:.2f} people")
print("(This means the AI's crowd predictions are typically off by only this many people)")

# 7. Serialize and Export the Model
joblib.dump(rf_model, 'models/rf_crowd_model.pkl')
print("\n✅ Success! Saved trained model to 'models/rf_crowd_model.pkl'")

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import joblib

# 1. Load the Text Data
print("Loading NLP data...")
df_reviews = pd.read_csv('data/heritage_tourist_reviews.csv')

# 2. Encode the Target Labels (Positive, Negative, Neutral -> 0, 1, 2)
le_sentiment = LabelEncoder()
y = le_sentiment.fit_transform(df_reviews['Sentiment_Label'])
y_categorical = tf.keras.utils.to_categorical(y, num_classes=3) # Convert to One-Hot Encoding for DL

# Save this encoder so the web app knows what 0, 1, and 2 mean
joblib.dump(le_sentiment, 'models/sentiment_label_encoder.pkl')

# 3. DL Preprocessing: Tokenization & Padding
print("Tokenizing and padding text for Deep Learning...")
vocab_size = 5000  # Number of unique words to remember
max_length = 50    # Max length of a review

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(df_reviews['Review_Text'])
sequences = tokenizer.texts_to_sequences(df_reviews['Review_Text'])
X_padded = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')

# Save the tokenizer for the web app
joblib.dump(tokenizer, 'models/dl_tokenizer.pkl')

# 4. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_padded, y_categorical, test_size=0.2, random_state=42)

# 5. Build the Deep Neural Network Architecture
print("\nBuilding the Deep Learning Model...")
model = Sequential([
    # Embedding layer creates a dense mathematical vector for every word
    Embedding(vocab_size, 16, input_length=max_length),
    GlobalAveragePooling1D(),

    # Hidden Layers with ReLU activation
    Dense(24, activation='relu'),
    Dropout(0.2), # Dropout prevents the neural network from overfitting
    Dense(12, activation='relu'),

    # Output Layer: 3 nodes (Pos, Neg, Neu) using Softmax for probabilities
    Dense(3, activation='softmax')
])

# Compile the Neural Network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# 6. Train the Neural Network
print("\nTraining the Deep Neural Network...")
history = model.fit(
    X_train, y_train,
    epochs=15,
    validation_data=(X_test, y_test),
    verbose=1
)

# 7. Evaluate and Export
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\n--- Deep Learning NLP Evaluation ---")
print(f"Neural Network Test Accuracy: {accuracy * 100:.2f}%")

# Save the Deep Learning model (Note: Keras models save as .keras or .h5 files, not .pkl)
model.save('models/dl_sentiment_model.keras')
print("\n✅ Success! Saved Deep Learning model to 'models/dl_sentiment_model.keras'")

